"""Adding pagetag colum to page

Revision ID: ceceb822acb8
Revises: 3e43e0eecaf1
Create Date: 2018-09-30 16:01:21.361081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceceb822acb8'
down_revision = '3e43e0eecaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'tag')
    # ### end Alembic commands ###
